version: '3.8'

services:
  mariadb:
    image: mariadb:11.2
    container_name: personal-finance-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword123}
      MYSQL_DATABASE: ${DB_NAME:-personal_finance}
      MYSQL_USER: ${DB_USER:-finance_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-finance_user_password_2024}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - finance-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

  app:
    build: .
    container_name: personal-finance-app
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=${DB_NAME:-personal_finance}
      - DB_USER=${DB_USER:-finance_user}
      - DB_PASSWORD=${DB_PASSWORD:-finance_user_password_2024}
      - DB_SSL=false
      - APP_PORT=${APP_PORT:-3000}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_change_this_in_production}
    ports:
      - "${APP_PORT:-3000}:3000"
    networks:
      - finance-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mariadb_data:
    driver: local

networks:
  finance-network:
    driver: bridge